version: "3.8"

services:
  # Banco de dados PostgreSQL
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 8531
      POSTGRES_DB: dashboard_metrics
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # API Node.js
  node-api:
    build: ./backend/node-api
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: 8531
      DB_NAME: dashboard_metrics
      DB_PORT: 5432
      NODE_ENV: production
      PORT: 3000
    ports:
      - "3000:3000"

  # Servidor Web para Frontend (Nginx)
  frontend:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - node-api

volumes:
  postgres_data:
