version: "3.8"
services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: metricsdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"

  python-engine:
    build: ./backend/python-engine
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: metricsdb
      DB_PORT: 5432
    ports:
      - "5000:5000"

  node-api:
    build: ./backend/node-api
    restart: unless-stopped
    depends_on:
      - postgres
      - python-engine
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: metricsdb
      DB_PORT: 5432
      PORT: 3000
    ports:
      - "3000:3000"

volumes:
  postgres_data:
